"""add user_role and application_status enums

Revision ID: 9471f8b9237b
Revises: ab7c226c0afd
Create Date: 2026-01-12 20:11:30.012042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9471f8b9237b'
down_revision: Union[str, Sequence[str], None] = 'ab7c226c0afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    application_status = postgresql.ENUM("applied", "rejected", "accepted", name="application_status")
    application_status.create(op.get_bind(), checkfirst=True)
    user_role = postgresql.ENUM("admin", "employer", "candidate", name="user_role")
    user_role.create(op.get_bind(), checkfirst=True)
    op.alter_column('applications', 'status',
               existing_type=sa.VARCHAR(),
               type_=application_status,
               existing_nullable=False,
               postgresql_using="status::application_status")
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=user_role,
               existing_nullable=False,
               postgresql_using="role::user_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM("admin", "employer", "candidate", name="user_role"),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="role::text")
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM("applied", "rejected", "accepted", name="application_status"),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="status::text")
    application_status = postgresql.ENUM("applied", "rejected", "accepted", name="application_status")
    application_status.drop(op.get_bind(), checkfirst=True)
    user_role = postgresql.ENUM("admin", "employer", "candidate", name="user_role")
    user_role.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
